# This is a basic workflow to help you get started with Actions

name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "* * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: FikaStudio-code/metrics@main
        with:
          token: ${{ secrets.TOP_PREVIEW }}
